openapi: 3.1.0
info:
  title: p4pa-fileshare
  description: Api and Models
  version: "1.0.0"
paths:
  /ingestionflowfiles/{organizationId}:
    post:
      tags:
        - ingestion-flow-file
      summary: uploadIngestionFlowFile
      description: Service to store an ingestion flow file
      operationId: uploadIngestionFlowFile
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: ingestionFlowFileType
          in: query
          required: true
          schema:
            type: string
            enum:
              - RECEIPT
              - PAYMENTS_REPORTING
              - OPI
              - TREASURY_CSV
              - TREASURY_XLS
              - TREASURY_POSTE
      requestBody:
        content:
          'multipart/form-data':
            schema:
              required:
                - ingestionFlowFile
              type: object
              properties:
                ingestionFlowFile:
                  type: string
                  format: binary
      responses:
        '200':
          description: OK
