server:
  http: "\${SERVER_PORT:8080}"

spring:
    application:
      name: ${artifactId}
      version: ${version}
    jmx.enabled: true
    threads:
      virtual:
        enabled: "\${VIRTUAL_THREADS_ENABLED:true}"
    servlet:
      multipart:
        max-file-size: "\${MULTIPART_MAX_FILE_SIZE:50MB}"
        max-request-size: "\${MULTIPART_MAX_REQUEST_SIZE:50MB}"

management:
    endpoints:
      jmx:
        exposure.include: "*"
      web:
        exposure:
          include: health, info, prometheus, metrics
        base-path: /actuator
    endpoint:
      health:
        probes.enabled: true
        group:
          readiness.include: "*"
          liveness.include: livenessState,diskSpace,ping
      prometheus:
        enabled: true
    metrics:
      tags:
        application: ${artifactId}
      export:
        prometheus:
          enabled: true
          step: 1m
          descriptions: true
      enable:
        jvm: true
        process: true
        system: true
        http: true
        logback: true

folders:
  shared: "\${SHARED_FOLDER_ROOT:/shared}"
  tmp: "\${TMP_FOLDER:/tmp}"
  process-target-sub-folders:
    archive: "\${PROCESS_TARGET_SUB_FOLDER_ARCHIVE:archive}"
    errors: "\${PROCESS_TARGET_SUB_FOLDER_ERRORS:errors}"

rest:
  default-timeout:
    connect-millis: "\${DEFAULT_REST_CONNECT_TIMEOUT_MILLIS:60000}"
    read-millis: "\${DEFAULT_REST_READ_TIMEOUT_MILLIS:60000}"
  auth:
    base-url: "\${AUTH_SERVER_BASE_URL:}"
  organization:
    base-url: "\${ORGANIZATION_BASE_URL:}"

uploads:
  ingestion-flow-file:
    valid-extension: "\${INGESTION_FLOW_FILE_VALID_EXTENSION:.zip}"
